### ISSUE TITLE
Sharpshooter Revolver Crashes The Game

### ISSUE THREAD

**Issue by CluckCluckDonalsthe5th** [absolutelyaya/ultracraft#86] opened 2023-11-26 12:32 UTC

**Comment by absolutelyaya** [comment] 2023-11-26 16:39
I need some more information on the crash, like a crashlog.
Due to a lack of info I'll just assume this is a duplicate of #85

**Comment by CluckCluckDonalsthe5th** [comment] 2023-11-27 07:52
Oh Wait, I Think it IS A Duplicate of #85. Regardless, Here's The Crash Log: 
[crash-2023-11-26_17.33.02-server.txt](https://github.com/absolutelyaya/ultracraft/files/13471283/crash-2023-11-26_17.33.02-server.txt)

**Closed as completed** 2023-12-02 14:37 UTC
Labels: bug, duplicate
