### ISSUE TITLE
World became inaccessable after inserting a resource pack sound into a sound listener

### ISSUE THREAD

**Issue by SurelyNotClover** [absolutelyaya/ultracraft#125] opened 2024-05-09 10:45 UTC
After inserting "minecraft:sfx.error", my resource pack custom sound, into a sound listener, the game crashed the second it was activated and kept crashing at every subsequent attempt at loading the world. I fixed it by removing the sound listener with an external program (in my case, Amulet. MCEdit crashes too)
[Crash Logs.txt](https://github.com/absolutelyaya/ultracraft/files/15261198/Crash.Logs.txt) (Crash logs are separated by lines)

**Comment by absolutelyaya** [comment] 2024-05-09 10:56
It looks like the sounds identifier wasn't found in the sound registry, resulting in a nullref (this will be fixed)
Are you absolutely sure that the sound was added and loaded correctly ? If it was, it should appear in `/playsound`s tab-complete

**Comment by SurelyNotClover** [comment] 2024-05-09 10:57
Yes, there's a point in the map where that sound is played through a command block and I have used it multiple times

**Comment by absolutelyaya** [comment] 2024-05-09 11:00
I'll try looking into it further; hopefully I can figure that out and fix it for the next update

**Comment by SurelyNotClover** [comment] 2024-05-09 11:01
Also a room with that listener is no longer a room I suppose? Everything in the room reset and when I tried to size the room back to where it was, it said that "nothing is focused with a tag 'room' "

**Comment by absolutelyaya** [comment] 2024-05-09 11:52
alright, figured it out. I was loading sounds improperly, meaning custom resourcepack sounds couldn't ever have worked.. and since I just kinda assumed that if normal sounds work, resourcepack sounds should work as well, I didn't think to test that specifically. I'm very sorry for the inconvenience- It'll be fixed in the next update though

> nothing is focused with a tag 'room' 

That kinda sounds like it could be a desyncing issue; usually either rejoining the world, or worst case restarting the game *should* fix that, unless it's caused by something different I'm unaware of

**Closed as completed** 2024-06-01 12:22 UTC
Labels: bug
